# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pages.models

def create_defaults(apps, schema_editor):
    Section = apps.get_model("pages", "Section")
    Page = apps.get_model("pages", "Page")
    db_alias = schema_editor.connection.alias
    Section.objects.using(db_alias).bulk_create([
        Section(
            title="Home",
            slug="index.html",
            order=1,
            is_visible=True
        ),
        Section(
            title="About",
            slug="about",
            order=2,
            is_visible=True
        )
    ])
    Page.objects.using(db_alias).bulk_create([
        Page(
            title="Home",
            slug="index.html",
            body="<h1>Hello World!</h1>",
            is_visible=True,
            footer_link=True,
            section=Section.objects.using(db_alias).get(pk=1)
        ),
        Page(
            title="About",
            slug="about",
            body="<p>Tell me baby, what's your story?</p>",
            is_visible=True,
            footer_link=True,
            section=Section.objects.using(db_alias).get(pk=2)
        )
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('body', models.TextField()),
                ('is_visible', models.BooleanField(default=False)),
                ('footer_link', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=pages.models.section_default, unique=True)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.PROTECT, to='pages.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('section', 'order')]),
        ),
        migrations.RunPython(create_defaults),
    ]
