# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170802_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first',
            field=models.CharField(default='ABC', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='last',
            field=models.CharField(default='ABC', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-img'),
        ),
    ]
