# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170803_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='name_slug',
        ),
    ]
